### PR TITLE
Added a tutorial to the readme

### PR DESCRIPTION
**Pull request by chrisdevh**
This commit will add more examples to install and configure the theme and templates. Additionally, I added a quickstart example

### CODE REVIEW

**Review by fredrikpersson92 — APPROVED** [review]
Thanks for you effort, I think it looks good. I did not write as much as there are good guides on using UI Minimalist, which uses the exact same process. But this is good too.

**Comment by chrisdevh** [comment]
I think you need to merge it to your code base so it gets integrated, since there are no github actions set up, such that the merge will get automatically done if you approve it.

**Comment by fredrikpersson92** [comment]
Do I just click "Merge pull request"?

**Comment by chrisdevh** [comment]
Yes. There should not be any merge conflicts occring, since I only added the readme and pulled the latest changes.

**Pull request merged**
